[Interface]
Address = 10.254.0.2/24
ListenPort = 51820
PrivateKey = SPidnw3SR8RnIQshbyCDaqWuHZnBYTr4VSDrq7OfUmQ=


[Peer]
PublicKey = VFBUi9MMnwb86FMKlAs66o3MRtqfV0wjgbeUU7XWdDU=
AllowedIPs = 10.254.0.0/16
Endpoint = <IP_SERVIDOR>:51820