[Interface]
Address = 10.254.0.4/24
ListenPort = 51820
PrivateKey = 8K5QIUmNTl++GD40TvBrMK+7CtS6NOZ1QH8OQF9fTmU=


[Peer]
PublicKey = VFBUi9MMnwb86FMKlAs66o3MRtqfV0wjgbeUU7XWdDU=
AllowedIPs = 10.254.0.0/16
Endpoint = <IP_SERVIDOR>:51820