[Interface]
Address = 10.254.0.3/24
ListenPort = 51820
PrivateKey = yNnfaE5kSunrDD3UKC7wrGzhK3e6VfFJe1FSAO4nFEg=


[Peer]
PublicKey = VFBUi9MMnwb86FMKlAs66o3MRtqfV0wjgbeUU7XWdDU=
AllowedIPs = 10.254.0.0/16
Endpoint = <IP_SERVIDOR>:51820