[Interface]
Address = 10.254.0.1/24
ListenPort = 51820
PrivateKey = KHcgu/8VnW1Lf3K2Xd50uolyBa3uoe4AXcLT6UEVxVk=


[Peer]
PublicKey = cCr+lwy4uz1xsZ0fF9Oj/DmNdsPd99PnvbXLof6hf1g=
AllowedIPs = 10.254.0.2/32

[Peer]
PublicKey = R8lLX4Tm2POLcVY4IOOrEQRfcVObayZGpPCuifYCcys=
AllowedIPs = 10.254.0.3/32

[Peer]
PublicKey = OI3c4hZyAXnsbFwp+TuzqE0fxSdm1/q+Asbin3A4qmY=
AllowedIPs = 10.254.0.4/32