services:
  wireguard:
    build:
      context: .
    cap_add:
      - NET_ADMIN
      - DAC_OVERRIDE
    cap_drop:
      - ALL
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv6.conf.all.forwarding: "1"
    volumes:
      - ./artifacts/wg-server.conf:/etc/wireguard/wg0.conf:ro
